### ISSUE TITLE
generic_linear_algebra still calls deprecated trilinos wrappers

### ISSUE THREAD

**Issue by QiaoLei-88** [dealii/dealii#1207]
In file included from /Users/qiaol/Library/deal.II/include/deal.II/lac/generic_linear_algebra.h:139:
In file included from /Users/qiaol/Library/deal.II/include/deal.II/lac/trilinos_block_sparse_matrix.h:27:
/Users/qiaol/Library/deal.II/include/deal.II/lac/trilinos_sparse_matrix.h:2452:43: warning: 
      'row_partitioner' is deprecated [-Wdeprecated-declarations]

In file included from /Users/qiaol/Library/deal.II/include/deal.II/lac/generic_linear_algebra.h:139:
/Users/qiaol/Library/deal.II/include/deal.II/lac/trilinos_block_sparse_matrix.h:442:61: warning: 
      'domain_partitioner' is deprecated [-Wdeprecated-declarations]

In file included from /Users/qiaol/Library/deal.II/include/deal.II/lac/generic_linear_algebra.h:139:
/Users/qiaol/Library/deal.II/include/deal.II/lac/trilinos_block_sparse_matrix.h:458:60: warning: 
      'range_partitioner' is deprecated [-Wdeprecated-declarations]

**Comment by bangerth** [comment]
You only show where the header file was included, but not where that function is called. Can you post the whole warning message?

**Comment by tjhei** [comment]
Yes, I am happy to take a look if you post the details.

**Comment by QiaoLei-88** [comment]
A typical complete warning message is like this:

```
In file included from /Users/qiaol/Dropbox/qlPhd/NSolver/NSolver/source/solver/integrate_force.cpp:10:
In file included from /Users/qiaol/Dropbox/qlPhd/NSolver/NSolver/header/NSolver/solver/NSolver.h:53:
In file included from /Users/qiaol/Library/deal.II/include/deal.II/lac/generic_linear_algebra.h:139:
In file included from /Users/qiaol/Library/deal.II/include/deal.II/lac/trilinos_block_sparse_matrix.h:27:
/Users/qiaol/Library/deal.II/include/deal.II/lac/trilinos_sparse_matrix.h:2452:43: warning: 'row_partitioner' is deprecated
      [-Wdeprecated-declarations]
                                          row_partitioner(), false);
                                          ^
In file included from /Users/qiaol/Library/deal.II/include/deal.II/lac/trilinos_sparse_matrix.h/Users/qiaol/Dropbox/qlPhd/NSolver/NSolver/source/solver/NSolver.cpp::168729::
23In file included from :/Users/qiaol/Dropbox/qlPhd/NSolver/NSolver/header/NSolver/solver/NSolver.h :53:
noteIn file included from : /Users/qiaol/Library/deal.II/include/deal.II/lac/generic_linear_algebra.h:'row_partitioner'139 :
hasIn file included from  /Users/qiaol/Library/deal.II/include/deal.II/lac/trilinos_block_sparse_matrix.hbeen: 27explicitly:
 marked
      deprecated here
/Users/qiaol/Library/deal.II/include/deal.II/lac/trilinos_sparse_matrix.h:2452:43: warning: 'row_partitioner' is    const Epetra_Map &row_partitioner () const DEAL_II_DEPRECATED; 
deprecated
                      ^      
[-Wdeprecated-declarations]
                                          row_partitioner(), false);
                                          ^
/Users/qiaol/Library/deal.II/include/deal.II/lac/trilinos_sparse_matrix.h:1687:23: note: 'row_partitioner' has been explicitly marked
      deprecated here
    const Epetra_Map &row_partitioner () const DEAL_II_DEPRECATED;
```

>You only show where the header file was included, but not where that function is called.

The deprecated functions are invoked just from the header file 'lac/trilinos_block_sparse_matrix.h' rather than a *.cc source file because these functions are all inlined.

I think substitute the deprecated functions with corresponding new versions will address this issue. But I don't know how the new functions look like.

**Comment by tjhei** [comment]
see #1213

**Comment by bangerth** [comment]
Should be fixed now.

**Comment by QiaoLei-88** [comment]
Actually it's not fully fixed. 
trilinos_block_sparse_matrix.h still calls the deprecated domain_partitioner() and range_partitioner().

Building step-40 will trigger 
```
[100%] Building CXX object CMakeFiles/step-40.dir/step-40.cc.o
In file included from /Users/qiaol/devel/dealii/examples/step-40/step-40.cc:31:
In file included from /Users/qiaol/Library/deal.II/include/deal.II/lac/generic_linear_algebra.h:139:
/Users/qiaol/Library/deal.II/include/deal.II/lac/trilinos_block_sparse_matrix.h:442:61: warning: 
      'domain_partitioner' is deprecated [-Wdeprecated-declarations]
      domain_partitioner.push_back(this->sub_objects[0][c]->domain_partitioner());
                                                            ^
/Users/qiaol/Library/deal.II/include/deal.II/lac/trilinos_sparse_matrix.h:2630:17: note: 
      'domain_partitioner' has been explicitly marked deprecated here
  SparseMatrix::domain_partitioner () const
                ^
In file included from /Users/qiaol/devel/dealii/examples/step-40/step-40.cc:31:
In file included from /Users/qiaol/Library/deal.II/include/deal.II/lac/generic_linear_algebra.h:139:
/Users/qiaol/Library/deal.II/include/deal.II/lac/trilinos_block_sparse_matrix.h:458:60: warning: 
      'range_partitioner' is deprecated [-Wdeprecated-declarations]
      range_partitioner.push_back(this->sub_objects[r][0]->range_partitioner());
                                                           ^
/Users/qiaol/Library/deal.II/include/deal.II/lac/trilinos_sparse_matrix.h:2639:17: note: 
      'range_partitioner' has been explicitly marked deprecated here
  SparseMatrix::range_partitioner () const
```

**Comment by QiaoLei-88** [comment]
Another question just for curiosity:

trilinos_block_sparse_matrix.h is also included by lac/matrix_out.h
```
/lac/matrix_out.h:#  include <deal.II/lac/trilinos_block_sparse_matrix.h>
```
and matrix_out.h has corresponding matrix_out.cc.

Why building deal.II doesn't trigger these warnings?

**Comment by bangerth** [comment]
> trilinos_block_sparse_matrix.h is also included by lac/matrix_out.h
>
> |/lac/matrix_out.h:#  include <deal.II/lac/trilinos_block_sparse_matrix.h>
> |
>
> and matrix_out.h has corresponding matrix_out.cc.
>
> Why building deal.II doesn't trigger these warnings?

You only get the warning if anything that is being compiled actually *uses* 
the deprecated function. Just including a file doesn't trigger the warning.

**Comment by kronbichler** [comment]
@bangerth Just as a remark: I see the warning when trying to compile step-31.

**Comment by kronbichler** [comment]
@QiaoLei-88 As to why building deal.II does not trigger the warnings: Deprecation warnings only get enabled in code using deal.II, not while compiling the library itself.

**Comment by bangerth** [comment]
This should now be fixed by #1215. Please reopen if you find other places.
