### ISSUE TITLE
error with mappingQ in 3d for a cylindrical manifold

### ISSUE THREAD

**Issue by segonpin** [dealii/dealii#2473]
As reported here, [https://groups.google.com/forum/#!topic/dealii/vGo5HZunFJ8](https://groups.google.com/forum/#!topic/dealii/vGo5HZunFJ8) , something seems to be wrong when using the cylindrical manifold with the high order mapping. The main point is that the refinement of the 3d cylinder seems to work well in the upper and lower faces, but in the center of the geometry the mappingQ works worse. 

A 2d and 3d table of the area and volume, that must be the same in 2d and in 3d (as it is for degree 1 of the mapping, but fails for the others degrees):

```
Computation of Pi by the area(2d):
==============================
[deg]   [ TArea ]   [TA - PI]   [err(OA)]   [err(IA)]

 1  2.000e+00   1.142e+00   -9.457e-01  -1.959e-01
 2  3.105e+00   3.702e-02   -3.067e-02  -6.352e-03
 3  3.141e+00   5.893e-04   -4.882e-04  -1.011e-04
 4  3.142e+00   5.461e-06   -4.524e-06  -9.369e-07

Computation of Pi by the volumne(3d):
==============================
[deg]   [ TArea ]   [TA - PI]   [err(OA)]   [err(IA)]

 1  2.000e+00   1.142e+00   -9.457e-01  -1.959e-01
 2  3.105e+00   3.702e-02   4.829e-02   -8.532e-02
 3  3.111e+00   3.048e-02   6.233e-02   -9.281e-02
 4  3.140e+00   1.154e-03   8.867e-02   -8.982e-02
```

Where the areas or the red and blue regions in the following cylinder are calculated for the 3d figure, as inner_area (IA) and outer_area (OA), as well as the total area (TA). It is worth to notice that not only the volumen of the inner cylinder (red domain in next figure) is wrong, but also the volumen of the outer ring (blue domain).

Here we can see the cylinder in 3d splited by two with paraview, so we can see that the inner cylinder (in red) is bended

![3d_half_cylinder](https://cloud.githubusercontent.com/assets/15182222/14342961/17fdb670-fc9e-11e5-9c9c-c366c5bef85f.png)

And, just to have it more clear, here we see just the cylinder and the rest of the subdomain transparent

![3d_inner_cylinder](https://cloud.githubusercontent.com/assets/15182222/14343009/5373b6e6-fc9e-11e5-86e1-f02ec3c6660f.png)

Test program to reproduce the table and the figures follows.

```
// Testing grids with Manifolds by approximating pi.

#include <deal.II/base/quadrature_lib.h>
#include <deal.II/base/convergence_table.h>

#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/tria_accessor.h>
#include <deal.II/grid/tria_iterator.h>
#include <deal.II/grid/tria_boundary_lib.h>
#include <deal.II/grid/tria.h>
#include <deal.II/grid/manifold_lib.h>
#include <deal.II/grid/grid_out.h>

#include <deal.II/dofs/dof_handler.h>
#include <deal.II/dofs/dof_accessor.h>

#include <deal.II/fe/fe_q.h>
#include <deal.II/fe/fe_values.h>
#include <deal.II/fe/mapping_q.h>

#include <deal.II/numerics/data_out.h>

// And this again is C++:
#include <iostream>
#include <fstream>
#include <cmath>

using namespace dealii;
using namespace std;

// mainly Step-10 without computing the perimeter
namespace Step10
{
  using namespace dealii;

  const long double pi = 3.141592653589793238462643;
  const double inner_radius = 1./(1. + std::sqrt(2));
  const double true_inner_area = pi*std::pow(inner_radius,2);
  const double true_outer_area = pi - true_inner_area;

  template <int dim>
  void compute_pi_by_area (const unsigned int n_degree)
  {
    Assert(false, ExcMessage("Not Implemented"));
  }

  template <>
  void compute_pi_by_area<2> (const unsigned int n_degree)
  {
    std::cout << "Computation of Pi by the area(2d):" << std::endl
              << "==============================" << std::endl;
    printf("[deg] \t[ TArea ] \t[TA - PI] \t[err(OA)] \t[err(IA)]\n\n");

    Vector<double> zeros;

    const Point<2> center (0,0);
    const SphericalManifold<2> boundary_description (center);

    for (unsigned int degree=1; degree <= n_degree; ++degree)
    {
        const QGauss<2> quadrature(degree);
        Triangulation<2> triangulation;
        GridGenerator::hyper_ball (triangulation, Point< 2 >(0.0,0.0), 1.0 );

        const MappingQ<2> mapping (degree, true);
        const FE_Q<2>     dummy_fe (1);
        DoFHandler<2> dof_handler (triangulation);
        FEValues<2> fe_values (mapping, dummy_fe, quadrature,
                             update_quadrature_points | update_JxW_values);

        for (Triangulation<2>::active_cell_iterator
          cell = triangulation.begin_active(); cell!=triangulation.end(); ++cell) 
          {
            if (cell->center().square() < 1.e-5)
              cell->set_material_id(1);
            else
              cell->set_material_id(0);
          }

        Triangulation<2>::active_cell_iterator
          cell = triangulation.begin_active(),
          endc = triangulation.end();

        for (; cell!=endc; ++cell) 
          {
            if (cell->material_id() == 1)
            {
              if (not cell->point_inside(Point<2>()))
                cell->set_manifold_id(100);
            }
            else
            {
              cell->set_all_manifold_ids (100);
            }
          }

        triangulation.set_manifold (100, boundary_description);

        dof_handler.distribute_dofs (dummy_fe); 

        zeros.reinit(triangulation.n_active_cells());
        cell = dof_handler.begin_active();
        for (unsigned int i = 0; cell!=endc; ++cell, ++i)
        {
          zeros[i] = static_cast<double>(cell->material_id());
        }

        double area_inner = 0;
        double area_outer = 0;
        cell = dof_handler.begin_active();
        for (; cell!=endc; ++cell)
        {
          fe_values.reinit (cell);
          for (unsigned int i=0; i < fe_values.n_quadrature_points; ++i)
          {
            if (cell->material_id() == 1)
              area_inner += fe_values.JxW (i);
            else
            area_outer += fe_values.JxW (i);
          }
        }
        const double area_total = area_outer + area_inner;

        printf(" %d \t%.3e \t%.3e \t%.3e \t%.3e\n",
               degree,
               (double)area_total,
               (double)std::fabs(pi - area_total),
               (double)(area_outer - true_outer_area),
               (double)(area_inner - true_inner_area));

        { // plotting the grid
          DataOut<2> data_out;

          data_out.attach_dof_handler (dof_handler);

          std::ostringstream ss;              
          ss <<  "d2" << "_p" << degree;

          data_out.add_data_vector (zeros, std::string("grid") );

          std::ofstream o_vtk ( ss.str() + ".vtk" );
          data_out.build_patches (mapping, 5, DataOut<2>::curved_inner_cells );
          data_out.write_vtk (o_vtk);

          // eps
          GridOut grid_out;
          GridOutFlags::Eps<2> eps_flags(
            GridOutFlags::EpsFlagsBase::width,300,0.5,false,30,false,false,false, true);
          grid_out.set_flags(eps_flags);
          std::ofstream o_eps ("eps_" + ss.str() + ".eps");
          grid_out.write_eps (triangulation, o_eps, &mapping);
        }
    } // end for degree
  printf("\n");
  } // end compute_pi_by_area



  template <>
  void compute_pi_by_area<3> (const unsigned int n_degree)
  {
    std::cout << "Computation of Pi by the volumne(3d):" << std::endl
              << "==============================" << std::endl;
    printf("[deg] \t[ TArea ] \t[TA - PI] \t[err(OA)] \t[err(IA)]\n\n");

    Vector<double> zeros;
    const Point<3> center (0,0,0);
    const Point<3> dir (0,0,1);
    const CylindricalManifold<3> boundary_description (dir,center);

    for (unsigned int degree=1; degree <= n_degree; ++degree)
    {
        const QGauss<3> quadrature(degree);

        Triangulation<3> triangulation;
        Triangulation<2> tria_aux;
        GridGenerator::hyper_ball (tria_aux, Point< 2 >(0.0,0.0), 1.0 );
        GridGenerator::extrude_triangulation (tria_aux, 2, 1.0, triangulation);

        const MappingQ<3> mapping (degree, true);
        const FE_Q<3>     dummy_fe (1);

        DoFHandler<3> dof_handler (triangulation);
        FEValues<3> fe_values (mapping, dummy_fe, quadrature,
                             update_quadrature_points | update_JxW_values);

        for (Triangulation<3>::active_cell_iterator
          cell = triangulation.begin_active(); cell!=triangulation.end(); ++cell) 
          {
            if (cell->point_inside(Point<3>(0.0, 0.0, 0.5)))
              cell->set_material_id(1);
            else
              cell->set_material_id(0);
          }

        Triangulation<3>::active_cell_iterator
          cell = triangulation.begin_active(),
          endc = triangulation.end();

        for (; cell!=endc; ++cell) 
          {
            if (cell->material_id() == 0)
            //if (not cell->point_inside(Point<3>()))
              cell->set_all_manifold_ids (100); 
          }

        triangulation.set_manifold (100, boundary_description);

        dof_handler.distribute_dofs (dummy_fe); 

        zeros.reinit(triangulation.n_active_cells());
        cell = dof_handler.begin_active();
        for (unsigned int i = 0; cell!=endc; ++cell, ++i)
          zeros[i] = static_cast<double>(cell->material_id());

        double area_inner = 0;
        double area_outer = 0;
        cell = dof_handler.begin_active();
        for (; cell!=endc; ++cell)
        {
          fe_values.reinit (cell);
          for (unsigned int i=0; i < fe_values.n_quadrature_points; ++i)
          {
            if (cell->material_id() == 1)
              area_inner += fe_values.JxW (i);
            else
            area_outer += fe_values.JxW (i);
          }
        }
        const double area_total = area_outer + area_inner;

        printf(" %d \t%.3e \t%.3e \t%.3e \t%.3e\n",
               degree,
               (double)area_total,
               (double)std::fabs(pi - area_total),
               (double)(area_outer - true_outer_area),
               (double)(area_inner - true_inner_area));

        { // plotting the grid
          DataOut<3> data_out;
          data_out.attach_dof_handler (dof_handler);
          std::ostringstream ss;              
          ss << "d3" << "_p" << degree;
          data_out.add_data_vector (zeros, std::string("grid") );

          std::ofstream o_vtk ( ss.str() + ".vtk" );
          data_out.build_patches (mapping, 5, DataOut<3>::curved_inner_cells );
          data_out.write_vtk (o_vtk);

          // eps 
          /*GridOut grid_out;
          GridOutFlags::Eps<3> eps_flags(
            GridOutFlags::EpsFlagsBase::width,300,0.5,false,30,false);
          grid_out.set_flags(eps_flags);
          std::ofstream o_eps ("eps_" + ss.str() + ".eps");
          grid_out.write_eps (triangulation, o_eps, &mapping);*/
        }
    } // end for degree
  printf("\n");
  } // end compute_pi_by_area

} // end namespace

int main ()
{
  try
    {
      std::cout.precision (16);

      const unsigned int n_degree = 4;

      Step10::compute_pi_by_area<2> (n_degree);
      Step10::compute_pi_by_area<3> (n_degree);
    }
  catch (std::exception &exc)
    {
      std::cerr << std::endl << std::endl
                << "----------------------------------------------------"
                << std::endl;
      std::cerr << "Exception on processing: " << std::endl
                << exc.what() << std::endl
                << "Aborting!" << std::endl
                << "----------------------------------------------------"
                << std::endl;

      return 1;
    }
  catch (...)
    {
      std::cerr << std::endl << std::endl
                << "----------------------------------------------------"
                << std::endl;
      std::cerr << "Unknown exception!" << std::endl
                << "Aborting!" << std::endl
                << "----------------------------------------------------"
                << std::endl;
      return 1;
    }
  return 0;
}
```

**Comment by kronbichler** [comment]
I think this is the effect addressed by #2698. @segonpin please re-evaluated once #2698 is merged (should be tomorrow).

**Comment by segonpin** [comment]
Hi Martin @kronbichler , first of all thank you for the effort that you all are doing. I have run the test again, and I have seen that some things looks better, while the problem is not solved yet. I explain next.

When running the program I obtain the following results for the calculation of the areas:

```
Computation of Pi by the area(2d):
==============================
[deg] 	[ TArea ] 	[TA - PI] 	[err(OA)] 	[err(IA)]

 1 	2.000e+00 	1.142e+00 	-9.457e-01 	-1.959e-01
 2 	3.105e+00 	3.702e-02 	-3.067e-02 	-6.352e-03
 3 	3.141e+00 	5.893e-04 	-4.882e-04 	-1.011e-04
 4 	3.142e+00 	5.461e-06 	-4.524e-06 	-9.369e-07

Computation of Pi by the volumne(3d):
==============================
[deg] 	[ TArea ] 	[TA - PI] 	[err(OA)] 	[err(IA)]

 1 	2.000e+00 	1.142e+00 	-9.457e-01 	-1.959e-01
 2 	3.105e+00 	3.702e-02 	-3.067e-02 	-6.352e-03
 3 	3.111e+00 	3.048e-02 	-2.525e-02 	-5.230e-03
 4 	3.140e+00 	1.154e-03 	-9.561e-04 	-1.980e-04

```

where I can see that the error in the inner and outer Areas is smaller than before, while still the whole area produces the same errors as before. It looks that the interface between the two areas is better, but something is still not working, because for degrees beyond 2 the results in 3d are different from those of 2d. 

I have printed the results for degree 3 for 2d and 3d in order to see if the mesh is different, and indeed it is.

![degree_3_different_outer_mesh](https://cloud.githubusercontent.com/assets/15182222/16382050/863943d6-3c7f-11e6-80db-12f6be8e20d1.png)

This is in agreement with the fact that the errors for degree 3 in 3d does not improve much with respect to those of degree 2. Then I print the mesh in 3d for degree 4 and I get the following

![degree_4_inner_mesh](https://cloud.githubusercontent.com/assets/15182222/16382103/b6dd296c-3c7f-11e6-8c43-6e601b91351d.png)

In this last picture it seems that the mesh for the outer volume is improved (with a better mesh). I am not sure that the mesh in the inner cylinder should be like this, but this does not affect the calculations for the volume anyway.  I am not sure if what I expect is possible, but I think that the mesh in 3d should be like an extrusion of the 2d mesh. Am I wrong?

**Comment by bangerth** [comment]
This seems to be fixed now on the current dev sources. Picture of the grid:
![visit0000](https://cloud.githubusercontent.com/assets/7504421/21865742/9620444a-d804-11e6-86a3-e7dcef421025.png)

Also, the output is now like this (exactly the same in 2d and 3d):
```
Computation of Pi by the area(2d):
==============================
[deg]   [ TArea ]       [TA - PI]       [err(OA)]       [err(IA)]

 1      2.000e+00       1.142e+00       -9.457e-01      -1.959e-01
 2      3.105e+00       3.702e-02       -3.067e-02      -6.352e-03
 3      3.111e+00       3.048e-02       -2.525e-02      -5.230e-03
 4      3.140e+00       1.154e-03       -9.561e-04      -1.980e-04

Computation of Pi by the volumne(3d):
==============================
[deg]   [ TArea ]       [TA - PI]       [err(OA)]       [err(IA)]

 1      2.000e+00       1.142e+00       -9.457e-01      -1.959e-01
 2      3.105e+00       3.702e-02       -3.067e-02      -6.352e-03
 3      3.111e+00       3.048e-02       -2.525e-02      -5.230e-03
 4      3.140e+00       1.154e-03       -9.561e-04      -1.980e-04
```

@segonpin -- do you agree that this is correct?

**Comment by segonpin** [comment]
Hi @bangerth ! It makes sense to me that both solutions are the same, because the 3d geometry should be an extrusion of the 2d. Nevertheless, I am worry with the fact that now they are the same solution, but this solution is the worst possible one. 

The last results were

```
Computation of Pi by the area(2d):
==============================
[deg]   [ TArea ]   [TA - PI]   [err(OA)]   [err(IA)]

 1  2.000e+00   1.142e+00   -9.457e-01  -1.959e-01
 2  3.105e+00   3.702e-02   -3.067e-02  -6.352e-03
 3  3.141e+00   5.893e-04   -4.882e-04  -1.011e-04
 4  3.142e+00   5.461e-06   -4.524e-06  -9.369e-07

Computation of Pi by the volumne(3d):
==============================
[deg]   [ TArea ]   [TA - PI]   [err(OA)]   [err(IA)]

 1  2.000e+00   1.142e+00   -9.457e-01  -1.959e-01
 2  3.105e+00   3.702e-02   -3.067e-02  -6.352e-03
 3  3.111e+00   3.048e-02   -2.525e-02  -5.230e-03
 4  3.140e+00   1.154e-03   -9.561e-04  -1.980e-04
```
and now the 2d got worse, being equal to the previous 3d. I was expecting the 3d to get better instead. If I take the data from [step 10](https://www.dealii.org/developer/doxygen/deal.II/step_10.html) and keep only the coarser mesh in 2d increasing the degree, the errors match what I got in the 2d table over the columne [TA-PI]. 

```
Computation of Pi by the area:
==============================
Degree cells      eval.pi            error      
1        5      1.9999999999999993 1.1416e+00    - 
2        5      3.1045694996615865 3.7023e-02    - 
3        5      3.1410033851499310 5.8927e-04    - 
4        5      3.1415871927401127 5.4608e-06     - 
```
Thus, it looks like the last change may have change the results of step 10. I will try to update the library and run the examples to see what I get and I will write again. 

Thank you very much. 
Sebas.

**Comment by bangerth** [comment]
@segonpin -- great, thanks for being willing to chase this down further and look at where step-10 now stands.

I think it's progress that we now at least get the same results in 2d and 3d. This suggests that there is now only one bug (maybe) left, somewhere in dimension independent code. I think the fact that the interior cylinder was so distorted was definitely a bug. So I think we're making progress in some directions at least. That means that we now no longer have to deal with 3d stuff, but should be able to simply look at the 2d situation and figure out why that may have become worse over the past year or two.

There are still one other, mapping related, issue open that could be related: #1646. However, this appears to be fixed.

**Comment by segonpin** [comment]
Hej @bangerth , I agree that we are going in the right direction. Regarding step 10, I have updated the library and I got the following results for step 10:

```
Computation of Pi by the area:
==============================
Degree = 1
cells      eval.pi            error      
    5 1.9999999999999993 1.1416e+00    - 
   20 2.8284271247461890 3.1317e-01 1.87 
   80 3.0614674589207169 8.0125e-02 1.97 
  320 3.1214451522580506 2.0148e-02 1.99 
 1280 3.1365484905459375 5.0442e-03 2.00 
 5120 3.1403311569547512 1.2615e-03 2.00 

Degree = 2
cells      eval.pi            error      
    5 3.1045694996615856 3.7023e-02    - 
   20 3.1391475703122267 2.4451e-03 3.92 
   80 3.1414377167038290 1.5494e-04 3.98 
  320 3.1415829366418997 9.7169e-06 4.00 
 1280 3.1415920457576894 6.0783e-07 4.00 
 5120 3.1415926155921112 3.7998e-08 4.00 

Degree = 3
cells      eval.pi            error      
    5 3.1111111111111112 3.0482e-02    - 
   20 3.1412148625997043 3.7779e-04 6.33 
   80 3.1415870671248314 5.5865e-06 6.08 
  320 3.1415925674774461 8.6112e-08 6.02 
 1280 3.1415926522488249 1.3410e-09 6.00 
 5120 3.1415926535688579 2.0935e-11 6.00 

Degree = 4
cells      eval.pi            error      
    5 3.1404385623510613 1.1541e-03    - 
   20 3.1415889797492116 3.6738e-06 8.30 
   80 3.1415926399751797 1.3615e-08 8.08 
  320 3.1415926535373067 5.2486e-11 8.02 
 1280 3.1415926535895879 2.0510e-13 8.00 
 5120 3.1415926535897913 1.6931e-15 6.92 
```

but the results of [step 10](https://www.dealii.org/8.4.1/doxygen/deal.II/step_10.html) in the 8.4.1 is
```
Computation of Pi by the area:
==============================
Degree = 1
cells      eval.pi            error      
    5 1.9999999999999993 1.1416e+00    - 
   20 2.8284271247461894 3.1317e-01 1.87 
   80 3.0614674589207178 8.0125e-02 1.97 
  320 3.1214451522580520 2.0148e-02 1.99 
 1280 3.1365484905459393 5.0442e-03 2.00 
 5120 3.1403311569547534 1.2615e-03 2.00 
Degree = 2
cells      eval.pi            error      
    5 3.1045694996615865 3.7023e-02    - 
   20 3.1391475703122271 2.4451e-03 3.92 
   80 3.1414377167038303 1.5494e-04 3.98 
  320 3.1415829366419015 9.7169e-06 4.00 
 1280 3.1415920457576911 6.0783e-07 4.00 
 5120 3.1415926155921139 3.7998e-08 4.00 
Degree = 3
cells      eval.pi            error      
    5 3.1410033851499310 5.8927e-04    - 
   20 3.1415830393583861 9.6142e-06 5.94 
   80 3.1415925017363837 1.5185e-07 5.98 
  320 3.1415926512106722 2.3791e-09 6.00 
 1280 3.1415926535525962 3.7197e-11 6.00 
 5120 3.1415926535892140 5.7923e-13 6.00 
Degree = 4
cells      eval.pi            error       
    5 3.1415871927401127 5.4608e-06     - 
   20 3.1415926314742437 2.2116e-08  7.95 
   80 3.1415926535026228 8.7170e-11  7.99 
  320 3.1415926535894529 3.4036e-13  8.00 
 1280 3.1415926535897927 2.9187e-16 10.19 
 5120 3.1415926535897944 1.3509e-15 -2.21 
```
so for degree 3 or 4 the results are worse. The fact that we can restrict ourselves to 2d to find the error is for sure a good thing. I will try to find a minimal possible example that keeps giving a different result, so this could maybe help to find the bug. 

I will also try to understand if there is any test that has failed related to step 10 (I do not know if these tests actually exists yet). I will check this things and then I will write again.

**Comment by segonpin** [comment]
Hej @bangerth , I agree that we are going in the right direction. Regarding step 10, I have updated the library and I got the following results for step 10:

```
Computation of Pi by the area:
==============================
Degree = 1
cells      eval.pi            error      
    5 1.9999999999999993 1.1416e+00    - 
   20 2.8284271247461890 3.1317e-01 1.87 
   80 3.0614674589207169 8.0125e-02 1.97 
  320 3.1214451522580506 2.0148e-02 1.99 
 1280 3.1365484905459375 5.0442e-03 2.00 
 5120 3.1403311569547512 1.2615e-03 2.00 

Degree = 2
cells      eval.pi            error      
    5 3.1045694996615856 3.7023e-02    - 
   20 3.1391475703122267 2.4451e-03 3.92 
   80 3.1414377167038290 1.5494e-04 3.98 
  320 3.1415829366418997 9.7169e-06 4.00 
 1280 3.1415920457576894 6.0783e-07 4.00 
 5120 3.1415926155921112 3.7998e-08 4.00 

Degree = 3
cells      eval.pi            error      
    5 3.1111111111111112 3.0482e-02    - 
   20 3.1412148625997043 3.7779e-04 6.33 
   80 3.1415870671248314 5.5865e-06 6.08 
  320 3.1415925674774461 8.6112e-08 6.02 
 1280 3.1415926522488249 1.3410e-09 6.00 
 5120 3.1415926535688579 2.0935e-11 6.00 

Degree = 4
cells      eval.pi            error      
    5 3.1404385623510613 1.1541e-03    - 
   20 3.1415889797492116 3.6738e-06 8.30 
   80 3.1415926399751797 1.3615e-08 8.08 
  320 3.1415926535373067 5.2486e-11 8.02 
 1280 3.1415926535895879 2.0510e-13 8.00 
 5120 3.1415926535897913 1.6931e-15 6.92 
```

but the results of [step 10](https://www.dealii.org/8.4.1/doxygen/deal.II/step_10.html) in the 8.4.1 is
```
Computation of Pi by the area:
==============================
Degree = 1
cells      eval.pi            error      
    5 1.9999999999999993 1.1416e+00    - 
   20 2.8284271247461894 3.1317e-01 1.87 
   80 3.0614674589207178 8.0125e-02 1.97 
  320 3.1214451522580520 2.0148e-02 1.99 
 1280 3.1365484905459393 5.0442e-03 2.00 
 5120 3.1403311569547534 1.2615e-03 2.00 
Degree = 2
cells      eval.pi            error      
    5 3.1045694996615865 3.7023e-02    - 
   20 3.1391475703122271 2.4451e-03 3.92 
   80 3.1414377167038303 1.5494e-04 3.98 
  320 3.1415829366419015 9.7169e-06 4.00 
 1280 3.1415920457576911 6.0783e-07 4.00 
 5120 3.1415926155921139 3.7998e-08 4.00 
Degree = 3
cells      eval.pi            error      
    5 3.1410033851499310 5.8927e-04    - 
   20 3.1415830393583861 9.6142e-06 5.94 
   80 3.1415925017363837 1.5185e-07 5.98 
  320 3.1415926512106722 2.3791e-09 6.00 
 1280 3.1415926535525962 3.7197e-11 6.00 
 5120 3.1415926535892140 5.7923e-13 6.00 
Degree = 4
cells      eval.pi            error       
    5 3.1415871927401127 5.4608e-06     - 
   20 3.1415926314742437 2.2116e-08  7.95 
   80 3.1415926535026228 8.7170e-11  7.99 
  320 3.1415926535894529 3.4036e-13  8.00 
 1280 3.1415926535897927 2.9187e-16 10.19 
 5120 3.1415926535897944 1.3509e-15 -2.21 
```
so for degree 3 or 4 the results are worse. The fact that we can restrict ourselves to 2d to find the error is for sure a good thing. I will try to find a minimal possible example that keeps giving a different result, so this could maybe help to find the bug. 

I will also try to understand if there is any test that has failed related to step 10 (I do not know if these tests actually exists yet). I will check this things and then I will write again.

**Comment by bangerth** [comment]
That is interesting: the convergence order is correct, just the absolute magnitude of the error is now larger. 

Do you know how to bisect the history of a git repository? It would be interesting to find which patch exactly caused this. In essence, I think this could be done by just reducing the test to p=3 and the very first mesh, because you're already getting a different number there. No need to look at the results too closely -- that one number is already indicative of it all, I believe. Such a simple test would help which commit or pull request caused the issue. If you wanted to look into this, that would be great -- I think it would help pin down where exactly the issue is, because it must be in the code changed by this one commit -- no poking around in a few hundred thousand lines of code necessary.

**Comment by bangerth** [comment]
Alternatively, you could see if #2698 was the cause by checking just before and after that was merged. I would not be surprised if that was the case.

**Comment by segonpin** [comment]
Hej, I am just reading about the bisect, and I think I understand it (it is like Bolzano theorem). I will try to find which commit is the one giving the error. I believe that I have to recompile the library for every commit (which takes a while), but I think it can be automatise with a bash script that also run the tests for p=3 and the first mesh to find the error. I will have to wait till Monday because I only have dealii at the computer of the office. Is it ok?

**Comment by bangerth** [comment]
Yes, correct: you need to write a little script that just recompiles everything, runs your simplified test, and either returns 0 or 1 depending on which output it produces. If you've got this set up, let it run overnight.

**Comment by segonpin** [comment]
Hi! I prepared the small script to automatize the git-bisect, and the output has been:

```
cd54f69fa348ad861e6a8fad332512446d5e6bf2 is the first bad commit
bisect run success
```

and then I asked what was this commit about

```
$ git show cd54f69fa348ad861e6a8fad332512446d5e6bf2
commit cd54f69fa348ad861e6a8fad332512446d5e6bf2
Merge: 70743bf 7c7527a
Author: David Wells <drwells@vt.edu>
Date:   Mon Sep 12 09:57:53 2016 -0400

    Merge pull request #3103 from bangerth/add-message-to-exceptions
    
    Provide error texts to more exceptions.
```

And I also asked the difference between this commit and the previous one
```
$ git diff cd54f69fa348ad861e6a8fad332512446d5e6bf2^ cd54f69fa348ad861e6a8fad332512446d5e6bf2
diff --git a/include/deal.II/base/data_out_base.h b/include/deal.II/base/data_out_base.h
index bbc8855..38725b0 100644
--- a/include/deal.II/base/data_out_base.h
+++ b/include/deal.II/base/data_out_base.h
@@ -1861,11 +1861,17 @@ namespace DataOutBase
   /**
    * An output function did not receive any patches for writing.
    */
-  DeclException0 (ExcNoPatches);
+  DeclExceptionMsg (ExcNoPatches,
+                    "You are trying to write graphical data into a file, but "
+                    "no data is available in the intermediate format that "
+                    "the DataOutBase functions require. Did you forget to "
+                    "call a function such as DataOut::build_patches()?");
   /**
    * Exception
    */
-  DeclException0 (ExcTecplotAPIError);
+  DeclExceptionMsg (ExcTecplotAPIError,
+                    "The error code of one of the Tecplot functions was "
+                    "not zero as expected.");
   /**
    * Exception
    */
@@ -2647,10 +2653,6 @@ public:
   /**
    * Exception
    */
-  DeclException0 (ExcNoPatches);
-  /**
-   * Exception
-   */
   DeclException0 (ExcIncompatibleDatasetNames);
   /**
    * Exception
diff --git a/source/base/data_out_base.cc b/source/base/data_out_base.cc
index 031e407..072c99b 100644
--- a/source/base/data_out_base.cc
+++ b/source/base/data_out_base.cc
@@ -7420,8 +7420,8 @@ merge (const DataOutReader<dim,spacedim> &source)
 
 
   const std::vector<Patch> source_patches = source.get_patches ();
-  Assert (patches.size () != 0,        ExcNoPatches ());
-  Assert (source_patches.size () != 0, ExcNoPatches ());
+  Assert (patches.size () != 0,        DataOutBase::ExcNoPatches ());
+  Assert (source_patches.size () != 0, DataOutBase::ExcNoPatches ());
   // check equality of component
   // names
   Assert (get_dataset_names() == source.get_dataset_names(),
```

But this does not make any sense. If anybody can help, I have prepared a repository with the scripts that I have used at [using git-bisect](https://github.com/segonpin/using-git-bisect/blob/master/README.md). At each iteration I have all the output of compiling the library so I am not able to see what the messages were (too much output), but I have seen (when still running) that I got some tests well and others wrong. I will try to run the bisect again and save the output to see if I can see anything else and I will write again. Thanks.

**Comment by masterleinad** [comment]
I was testing with `int failed = (std::fabs(area-pi)<1.e-5)?0:1;` and `degree=4`.
The result I get is

> df22186f87b1e47ec9f90054b761754622186941 is the first bad commit
> commit df22186f87b1e47ec9f90054b761754622186941
> Author: Luca Heltai <luca.heltai@sissa.it>
> Date:   Thu Sep 22 13:50:48 2016 +0000
> 
>     Implemented Praveen fix.
It seems that #3148 is guilty. The bisect search output was

> git bisect start
> bad: [cd97ee2f68bf4e6a21cbf138de9355d4977c8ce3] Merge pull request #3803 from tamiko/a_default_parameter
> bad: [cd97ee2f68bf4e6a21cbf138de9355d4977c8ce3] Merge pull request #3803 from tamiko/a_default_parameter
> good: [cd54f69fa348ad861e6a8fad332512446d5e6bf2] Merge pull request #3103 from bangerth/add-message-to-exceptions
> bad: [d7bf032f0243efde2c1df38ec93a79a86019bd0c] Merge pull request #3458 from bangerth/rename-variables
> bad: [a043197205913c2f979f179e8fbab1c7866bd37c] Merge pull request #3214 from bangerth/doc-update
> bad: [0bd1f08284fc066c2e9fa5280b5771315ac16048] Update the description of ConstraintMatrix::print().
> good: [6391774e3c10f5ec2fe92c8e1a3aeb34150aa361] Merge pull request #3088 from tamiko/fix_cmake_macros
> good: [ea0d225b57043ac0ebe9f8ccd46b201c473ae91e] Merge pull request #3153 from drwells/prefer-vector-to-list-2
> bad: [6c12995b4a9dc9f3cf55c6e490a97fb2533aaf26] Merge pull request #3148 from luca-heltai/fix-spherical-manifold
> good: [95b09cd611d4116d18b77c9df6c22679c2ae169f] Merge pull request #3156 from bangerth/fix-typo
> good: [9df86e6b6f4c15ad4a9878ccc28239a3804aea9a] Merge pull request #3157 from bangerth/doc-update-46
> good: [547634b42ecb908642f7431225c2d5b556a7fea8] Move some changes from 'general changes' to 'specific improvements'.
> bad: [df22186f87b1e47ec9f90054b761754622186941] Implemented Praveen fix.
> first bad commit: [df22186f87b1e47ec9f90054b761754622186941] Implemented Praveen fix.

**Comment by kronbichler** [comment]
I think this should be fixed for a few months already with #4483. @segonpin did you try a recent deal.II version?

**Comment by masterleinad** [comment]
For `step-10` I now get
```
Degree = 1
cells      eval.pi            error      
    5 2.8284271247461898 3.1317e-01    - 
   20 3.0614674589207178 8.0125e-02 1.97 
   80 3.1214451522580520 2.0148e-02 1.99 
  320 3.1365484905459389 5.0442e-03 2.00 
 1280 3.1403311569547525 1.2615e-03 2.00 
 5120 3.1412772509327724 3.1540e-04 2.00 

Degree = 2
cells      eval.pi            error      
    5 3.1248930668550594 1.6700e-02    - 
   20 3.1404050605605454 1.1876e-03 3.81 
   80 3.1415157631807014 7.6890e-05 3.95 
  320 3.1415878042798613 4.8493e-06 3.99 
 1280 3.1415923498174529 3.0377e-07 4.00 
 5120 3.1415926345931995 1.8997e-08 4.00 

Degree = 3
cells      eval.pi            error      
    5 3.1414940401456053 9.8613e-05    - 
   20 3.1415913432549152 1.3103e-06 6.23 
   80 3.1415926341726914 1.9417e-08 6.08 
  320 3.1415926532906902 2.9910e-10 6.02 
 1280 3.1415926535851360 4.6574e-12 6.00 
 5120 3.1415926535897198 7.3592e-14 5.98 

Degree = 4
cells      eval.pi            error       
    5 3.1415921029432567 5.5065e-07     - 
   20 3.1415926513737600 2.2160e-09  7.96 
   80 3.1415926535810712 8.7222e-12  7.99 
  320 3.1415926535897589 3.4220e-14  7.99 
 1280 3.1415926535897927 4.6252e-16  6.21 
 5120 3.1415926535897927 6.8803e-16 -0.57 
```
so we are better both than 8.4.1 and the previous developer version (especially for `degree>=3`).
The results for the other test are:
```
Computation of Pi by the area(2d):
==============================
[deg] 	[ TArea ] 	[TA - PI] 	[err(OA)] 	[err(IA)]

 1 	2.000e+00 	1.142e+00 	-9.457e-01 	-1.959e-01
 2 	3.105e+00 	3.702e-02 	-3.067e-02 	-6.352e-03
 3 	3.141e+00 	5.893e-04 	-4.882e-04 	-1.011e-04
 4 	3.142e+00 	5.461e-06 	-4.524e-06 	-9.369e-07

Computation of Pi by the volumne(3d):
==============================
[deg] 	[ TArea ] 	[TA - PI] 	[err(OA)] 	[err(IA)]

 1 	2.000e+00 	1.142e+00 	-9.457e-01 	-1.959e-01
 2 	3.105e+00 	3.702e-02 	-3.067e-02 	-6.352e-03
 3 	3.141e+00 	5.893e-04 	-4.882e-04 	-1.011e-04
 4 	3.142e+00 	5.461e-06 	-4.524e-06 	-9.369e-07
```
So we get the same (good) results in 3D and 2D which coincide with the original 2D errors.

Let's close this.

**Comment by bangerth** [comment]
Nice!
