### ISSUE TITLE
Make hp::DoFHandler work with parallel::distributed::Triangulation

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3511]
#1366 already asks for extending `hp::DoFHandler` for shared triangulations. But we also want it to work for completely parallel triangulations, of course.

I've created a project for this here: https://github.com/dealii/dealii/projects/5 . However, I find the "project" format awkward to use because it does not allow referencing projects from pull requests, and the GUI is also awkward because one gets into trouble with project that want more space than is visible on the screen in any given column. Consequently, here is my TODO list for getting there (help of course appreciated!):

 
- [x]  Go through the internal::DoFHandler::Policy namespace and understand the structure there. This includes which operations are available in the PolicyBase class and how work is dispatched between the sequential, shared, and parallel cases.

- [x]  As appropriate clean up code.

- [x]  Create a similar structure for hp::DoFHandler where the major operations are dispatched to a separate set of classes. At first, simply create the base class and a class for the sequential case.

- [x]  Move existing code into the derived policy class for the sequential case.

- [x]  Create parallel, derived classes for the shared and distributed case. It may be easiest to deal with the shared case first (#1366, but will also require #1367). 

- [x]  Following the structure for `parallel::distributed::Triangulation` implemented for `::DoFHandler`, also implement something similar for the corresponding `hp::DoFHandler` policy. The issue here is going to be that one has to transfer variable amounts of data between cells because cells no longer have the same number of DoFs. The easiest way for the moment will be to just allocate buffers that have the size of the maximal amount of data, and just pad with zeros as appropriate. We have, for the moment, no other choice anyway because p4est only allows us to attach a fixed sized buffer to cells.

- [x] Support `parallel::distributed::SolutionTransfer`

- [ ] Provide a weighting mechanism for cells upon partitioning

- [x] Write tests!

**Comment by davydden** [comment]
> However, I find the "project" format awkward to use because it does not allow referencing projects from pull requests

You need to add PR/issue as a card into the project and then you will see on the right of the web interface (same as in this issue), which project is the PR/issue assigned to.

offtopic: to me the project are a better way because one can move the card into `In Progress` column which would indicate that one of the developers (or more) are working on it. One can also add more columns which better reflect the project needs. With issues it is also possible to indicate that someone is working on this using `Assigness`, but IMHO projects give a better overview of all relevant PRs and issues and Notes.

**Comment by drwells** [comment]
Should we have a milestone for this?

**Comment by bangerth** [comment]
@drwells -- sure, feel free to create one and attach the 3 issues to it. (I see that we also have a C++11 milestone; we should attach all of the issues marked with C++11 to it as well...)

**Comment by marekcapek** [comment]
@bangerth I am starting to look around the relevant code. I just do no know how to move a TODO in https://github.com/dealii/dealii/projects/5 from "In progress" state, however you have complained about the project format. Maybe it is the responsibility of an "administrator". The list seems to me comprehensible.

**Comment by bangerth** [comment]
Yes, it looks like you need to be an administrator for this. I think the people who work on this are few enough that we don't have to worry too much about stepping on each other's feet. Just post progress reports here, and link any pull requests to this one.

When you read through code and you don't understand anything, or see anything that could be done better, or want to fix/expand a comment, please make that into pull requests. Whenever I read code, I almost always find things that I think can help improve the state of the code, and take the time to clean these things up so the next person doesn't stumble over them any more.

**Comment by drwells** [comment]
@bangerth I should have been more specific in what I meant. I meant that should we tag this with a 9.0 release?

**Comment by bangerth** [comment]
@drwells -- sure, maybe. I'm not sure we'll get it ready by then :-)

**Comment by tjhei** [comment]
One argument against your suggested approach is that we will have an explosion of the number of policies.

For example, we would need a different policy for each kind of triangulation (shared, distributed, etc.). I am still planning to have a third kind of parallel triangulation and now have a student to work on it (distributed storage but statically partitioned, not with p4est). Second, we would need to reimplement new policies for geometric multigrid for each combination we want to support.

A different approach would be to a) remove the normal DoFHandler and always use the hp version, b) make the parallel policy independent of the underlying parallel distribution strategy, so that we don't rely on p4est. For a) not to be a regression, we probably need to optimize the hp version quite a bit though. I am not sure how to approach b), maybe by having a second implementation of a parallel version and restructuring the policies in the process.

Thoughts on how we can minimize these issues?

**Comment by drwells** [comment]
Though I am not involved in any of these efforts it is worth noting that in #2000 @kronbichler proposed completely redoing DoFHandler along these lines. It might be better to start there.

**Comment by bangerth** [comment]
@tjhei -- I neither disagree nor agree with you. One way or the other, the code for the hp case has to be written, presumably by copying the existing code and extending it for the hp case. If we want to throw the existing implementation away at a later time, that's ok with me. I think that creating a parallel policy structure for hp is not actually going to be much work to begin with: it just involves moving around some code.

Regarding other triangulations: I think the effort is actually not all that large if you refactor and/or do derived classes. I don't recall how we supported the `shared::Triangulation` case, but in principle, all it should have taken is (i) inserting an `if(cell->is_locally_owned())` in the policy class that deals with sequential classes, and then (ii) derive  a separate class from the sequential one that calls the function in the base class and then does whatever is necessary in the parallel case. If done right, there shouldn't be much duplicated code, and I think the same can be done if you had statically partitioned triangulations, for example. It's just a question of how to properly refactor code.

**Comment by marekcapek** [comment]
@bangerth    I am trying to move the serial functionality in hp into a file, which contains "policy" like structures (i.e. like in non-hp dof_handler_policy.cc/h ).  I want to be able to compile my new features in such a way, which does not require compilation of whole dealii library.   I have tried to run some of the targets in
/dealii/source/hp/Makefile

However the build failed, error message:                                                                                                           **fatal error: dof_handler.inst: No such file or directory compilation terminated.**

I have already run cmake, therefore the Makefiles were correctly generated.  
Or is it necessary to compile whole library and then run the compilation process on each change in hp-directory? The build process should then pick up only the changes in the hp-directory.

**Comment by drwells** [comment]
@marekcapek one unadvertised feature of the CMake system is that you can do

```
$ make -j4 obj_hp_debug
```

to just compile part of the library (in this case the debug hp object files). I think that will do what you want.

**Comment by marekcapek** [comment]
@drwells it works, thank You

**Comment by kronbichler** [comment]
@bangerth Since you seem to have started working towards extending `hp::DoFHandler` for the parallel case: I just want to re-inforce @tjhei's opinion that we should definitely try to go towards a single `DoFHandler` class that can handle a `hp::FECollection` in the end. Now you might be moving towards a code where the `hp::DoFHandler` is sufficiently capable that we can later disable `DoFHandler`. If we implement the hp data structures right the computational overhead (compute-wise and memory-wise) will be small except for maybe `FE_DGQ(0)` or `FE_Nothing` for which we do not care because the triangulation takes so much more memory anyway. Some of the design points are given in #2000. I guess #4533 and #4534 do not hurt. But it definitely does not make sense to support two dof handler types as soon as hp DoFHandler can handle the parallel case for more than the transition period. It's 4500+ lines of code that would just do the same thing, and it's not really simple code parts.

**Comment by bangerth** [comment]
Yes, I agree with the aspirational goal of merging the two `DoFHandler` classes. That said, it's not just support for parallel computations that's missing in `hp::DoFHandler`, but also support for multigrid. We're still a ways off.

My goals for all of these cleanups is (i) to familiarize myself again with the code base so I can adapt it to the hp case, and (ii) to clean it up so that I can share some of it with what I want to do for the `hp::DoFHandler`. For example, the class I rewrote slightly in #4528 (`CellDataTransferBuffer`) is something that is entirely generic and can be reused for the `hp` case -- which is exactly what I'm going to do.

**Comment by kronbichler** [comment]
I agree, I justed wanted to make sure that we have similar goals. :-)

**Comment by kronbichler** [comment]
We have quite some open hp-related PRs and issues for the 9.1 milestone, so I take the opportunity to put this up here. @bangerth and @marcfehling how is your assessment of what can get finished before we close the merge window for tomorrow? We can always adjust the milestone for parts of the code.

**Comment by marcfehling** [comment]
We should definitely merge #7933 and #8072 for the upcoming release, which will finalize the interface for p-adaptation.

I would suggest to postpone the other features on our roadmap #7515 for later (e.g. #7513).

**Comment by kronbichler** [comment]
We have now merged the outstanding pull requests. Thanks @marcfehling (and @bangerth) for the huge effort made to eventually cover this feature. I'm closing here.

**Comment by bangerth** [comment]
That was a heroic effort indeed, taking two years to complete. Thanks for everyone's help in writing patches, reviewing patches, and getting it done! I'm sure there are pieces still missing, but @marcfehling really pushed the whole thing over the finish line over the past year!

**Comment by jppelteret** [comment]
> @marcfehling really pushed the whole thing over the finish line over the past year

Awesome work @marcfehling. Thanks so much for taking the time and effort to do this!
