### ISSUE TITLE
Hang with 4+ billion DoFs

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#8937]
I am experiencing a deterministic hang for large problem sizes. This is likely related to #8929 but only appears to happen with 64bit indices and >2^32 DoFs. This happens on a branch that contains a bunch of barriers that seem to work around the crashes in #8929.
The offending function in the user code is
```
dealii::LinearAlgebra::distributed::BlockVector<double> u(2);
matrix_free_operator.initialize_dof_vector(u);
u = 0; // <-- this completes, at least on rank 0
constraints.distribute(u); // <- does not finish on rank 0
```

I haven't been able to find the exact place inside deal.II but I realized that the call stack could be something like
```
Partitioner::Partitioner()
Vector<Number, MemorySpaceType>::reinit(
      const IndexSet &locally_owned_indices,
      const IndexSet &ghost_indices,
      const MPI_Comm  communicator)
internal::import_vector_with_ghost_elements()
AffineConstraints<number>::distribute(VectorType &vec) const
```
so this could also be inside ConsensusAlgorithm again.

@peterrum @kronbichler have you done any runs with >4 billion DoFs recently? You do some trickery with 32 bit indices in the Paritioner. Any suggestions on where to look? I tried switching to PEX but that doesn't help. #8936 also doesn't make a difference.

**Comment by tjhei** [comment]
I am also a bit disappointed that we run an expensive consensus algorithm every time we call constraints.distribute(). :-(

**Comment by tjhei** [comment]
Got it, the call stacks are:
```
#0  PMPI_Probe (source=51709264, tag=0, comm=0, status=0xb)
    at ../../src/mpid/ch4/netmod/include/../ofi/ofi_impl.h:688
#1  0x00002b9d1647108e in dealii::Utilities::MPI::internal::ComputeIndexOwner::Dictionary::reinit(dealii::IndexSet const&, int const&) ()
   from /scratch1/02578/theister/env5/deal-64/lib/libdeal_II.so.9.2.0-pre
#2  0x00002b9d164fd2ab in dealii::Utilities::MPI::Partitioner::set_ghost_indices(dealii::IndexSet const&, dealii::IndexSet const&) ()
   from /scratch1/02578/theister/env5/deal-64/lib/libdeal_II.so.9.2.0-pre
#3  0x00002b9d164fc0c0 in dealii::Utilities::MPI::Partitioner::Partitioner(dealii::IndexSet const&, dealii::IndexSet const&, int) ()
   from /scratch1/02578/theister/env5/deal-64/lib/libdeal_II.so.9.2.0-pre
#4  0x00002b9d15e8e1e6 in dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>::reinit(dealii::IndexSet const&, dealii::IndexSet const&, int) ()
   from /scratch1/02578/theister/env5/deal-64/lib/libdeal_II.so.9.2.0-pre
#5  0x00002b9d15b1477d in void dealii::AffineConstraints<double>::distribute<dealii::LinearAlgebra::distributed::BlockVector<double> >(dealii::LinearAlgebra::distributed::BlockVector<double>&) const () from /scratch1/02578/theister/env5/deal-64/lib/libdeal_II.so.9.2.0-pre
#6  0x00000000012c9d9d in aspect::StokesMatrixFreeHandler<3>::correct_stokes_rhs() ()
#7  0x000000000121677f in aspect::Simulator<3>::solve_first_timestep_only_single_stokes() ()
#8  0x000000000109652d in aspect::Simulator<3>::solve_timestep() ()
#9  0x000000000108ad16 in aspect::Simulator<3>::run() ()
#10 0x0000000000abf060 in run_simulator<3> ()
#11 0x0000000000aa63ee in main ()
```
and
```
#14 0x00002abac3750e9d in PMPI_Reduce_scatter_block (sendbuf=0x7, recvbuf=0xe2f62, recvcount=0, 
    datatype=929634, op=10000000, comm=1033756807)
    at ../../src/mpi/coll/reduce_scatter_block/reduce_scatter_block.c:408
#15 0x00002ababd5aa83f in dealii::Utilities::MPI::compute_point_to_point_communication_pattern(int const&, std::vector<unsigned int, std::allocator<unsigned int> > const&) ()
   from /scratch1/02578/theister/env5/deal-64/lib/libdeal_II.so.9.2.0-pre
#16 0x00002ababd5b274b in dealii::Utilities::MPI::ConsensusAlgorithm_PEX<std::pair<unsigned long long, unsigned long long>, unsigned int>::start_communication() ()
   from /scratch1/02578/theister/env5/deal-64/lib/libdeal_II.so.9.2.0-pre
#17 0x00002ababd5b1f33 in dealii::Utilities::MPI::ConsensusAlgorithm_PEX<std::pair<unsigned long long, unsigned long long>, unsigned int>::run() ()
   from /scratch1/02578/theister/env5/deal-64/lib/libdeal_II.so.9.2.0-pre
#18 0x00002ababd654349 in dealii::Utilities::MPI::Partitioner::set_ghost_indices(dealii::IndexSet const&, dealii::IndexSet const&) ()
   from /scratch1/02578/theister/env5/deal-64/lib/libdeal_II.so.9.2.0-pre
#19 0x00002ababd6530c0 in dealii::Utilities::MPI::Partitioner::Partitioner(dealii::IndexSet const&, dealii::IndexSet const&, int) ()
   from /scratch1/02578/theister/env5/deal-64/lib/libdeal_II.so.9.2.0-pre
#20 0x00002ababcfe51e6 in dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>::reinit(dealii::IndexSet const&, dealii::IndexSet const&, int) ()
   from /scratch1/02578/theister/env5/deal-64/lib/libdeal_II.so.9.2.0-pre
#21 0x00002ababcc6b77d in void dealii::AffineConstraints<double>::distribute<dealii::LinearAlgebra::distributed::BlockVector<double> >(dealii::LinearAlgebra::distributed::BlockVector<double>&) const () from /scratch1/02578/theister/env5/deal-64/lib/libdeal_II.so.9.2.0-pre
#22 0x00000000012c9d9d in aspect::StokesMatrixFreeHandler<3>::correct_stokes_rhs() ()
#23 0x000000000121677f in aspect::Simulator<3>::solve_first_timestep_only_single_stokes() ()
#24 0x000000000109652d in aspect::Simulator<3>::solve_timestep() ()
#25 0x000000000108ad16 in aspect::Simulator<3>::run() ()
#26 0x0000000000abf060 in run_simulator<3> ()
#27 0x0000000000aa63ee in main ()
```

**Comment by peterrum** [comment]
Is there a possibility to go back in history where #8772 was merged?

**Comment by tjhei** [comment]
I could, but I remember that the old all-to-all was terribly slow on this machine. :-(
I can see from the call stack what is going on and I will try to mess with the communicators for now. Will report back.

**Comment by bangerth** [comment]
@tjhei -- what's the news here? Is this fixed now?

**Comment by tjhei** [comment]
No, we still have a bug with >4 billion DoFs with adaptivity. It is no longer a hang like before, but we are seeing no convergence of the linear solver if hanging nodes are involved.

**Comment by peterrum** [comment]
> No, we still have a bug with >4 billion DoFs with adaptivity. It is no longer a hang like before, but we are seeing no convergence of the linear solver if hanging nodes are involved.

Is it reproducible or is there still a race condition?

**Comment by tjhei** [comment]
> Is it reproducible or is there still a race condition?

it is reproducible:
- I need 5000+ MPI ranks to fit the problem, but anything between 5k and 60k ranks fails
- I need 4+ billion velocity DoFs (but it is not a specific setup, various sizes between 4 and 8 billion fail)
- only when hanging nodes are in the system
- happens in debug and release mode
- happens with gcc 9 and intel 19
- At this point, I am not sure if the system is to blame.

Super annoying. :-(

**Comment by bangerth** [comment]
Oh dear. I'd trade you a deadlock or segfault for non-convergence...

If the testcase isn't too big and is reproducible, have you thought about asking others with access to large machines (@kronbichler) to run it there, to see whether it's a machine-related problem?

**Comment by kronbichler** [comment]
I definitely need to set up some adaptivity test on my machine again - I have run some back in March and then in October but I did not carefully analyze them.

**Comment by kronbichler** [comment]
I have reproduced the problem on our machine. I have started looking into the code and what could be the reason for a failure when we only do adaptivity. One place that looks suspicious (and was introduced in #8300, so fits in terms of timing) is this one:
https://github.com/dealii/dealii/blob/master/source/multigrid/mg_transfer_internal.cc#L266-L267

These should be `types::global_dof_index` as far as I can tell from the code around it (we later fill an `IndexSet` with them), so I have changed them locally. My job (384 nodes/18432 cores) sits in the queue right now. If the test succeeds, I will open a PR. If not, I will look more closely into the code to understand what is really going on and probably open a PR as well.

**Comment by peterrum** [comment]
> One place that looks suspicious (and was introduced in #8300, so fits in terms of timing)

Not again...

**Comment by tjhei** [comment]
I can confirm that #9528 fixes our test case! @kronbichler , we are grateful for your help in finally fixing this issue that we have been struggling with for many months! :fireworks: :champagne:

**Comment by tjhei** [comment]
Very satisfying to click "close" here. :-)

**Comment by peterrum** [comment]
> we have been struggling with for many months!

Sorry for the troubles caused by my first PR!

**Comment by bangerth** [comment]
@kronbichler -- there's a lesson I would like to learn from you here. Can you 
describe in a paragraph what your process was to find the location of the bug?

**Comment by kronbichler** [comment]
@bangerth you want me to reveal my recipe for finding the needle in the haystack? It feels not very heroic, maybe like placing magnets in the stomach of all cattle consuming the hay and then checking the magnets.
Metaphor aside, I knew from the experiment that @tjhei and @tcclevenger gave me that left preconditioning worked with GMRES whereas right did not. This indicated that the defect was small, so I suspected some wrong "boundary condition". Given that we knew it only happened for adaptive meshes and not for all meshes, this indicated the parts that happen on the so-called refinement edges. As this is only in `mg_constrained_dofs.h` and the place where we pick out the owned/remote indices for `MGLevelGlobalTransfer` which happens to be in `mg_transfer_internal.h`. Given that I know these algorithms very well - having written a substantial part of them together with @tjhei and the special ones for matrixfree myself in #2052 - I then simply opened the relevant files in the editor and looked through all uses of `unsigned int`.

**Comment by kronbichler** [comment]
> Sorry for the troubles caused by my first PR!

@peterrum you tackled a very difficult topic for the first PR. And the blame is just as much on us reviewers and co-authors who did not notice it...

**Comment by bangerth** [comment]
@kronbichler -- so it really just boils down to someone knowing the code and being able to put the symptoms in perspective. When @tjhei explained to me what was happening, I was pretty sure that it's a misplaced `unsigned int`, not some problem with non-compatible Stokes right hand sides, that was the cause. But I would not have known where to look. Nice to see that you could point your finger right where the issue was!

**Comment by kronbichler** [comment]
Yes indeed, I needed to be able to reduce the problem to check say 100 places in a few files only, rather than all 25000+ lines that contain and `unsigned int` in deal.II.
