### ISSUE TITLE
Current master does not build on github CI.

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#9853]
I was trying to create a new action to build the deal.II package for mac and a static library for windows, but the latest master does not build anymore on github ci... 

I'm not sure what went wrong.

**Comment by masterleinad** [comment]
I think this should be fixed by https://github.com/dealii/dealii/pull/9849.

**Comment by luca-heltai** [comment]
I still get the same problem:

https://github.com/luca-heltai/dealii/runs/568695580?check_suite_focus=true

This was rebased on top of 98ab8ec0b0 (#9849)

**Comment by masterleinad** [comment]
Hmm... looking at that link,
the Windows build fails with
```
No space left on device.
```
and the other two still show the error due to the unused variable which is fixed by that pull request.
